### ISSUE TITLE
Feature Request: Module to accept RF

### ISSUE THREAD

**Issue by ghost** [KidsDontPlay/Furnus#7]
Would it be possible to get a module to accept RF power? I've been enjoying Furnus so far, but it needs something to keep it viable in mid-game. After a certain point you either need an automated charcoal farm or you spend as much time digging for coal as for ore.

**Comment by KidsDontPlay** [comment]
I started with the intention of making a furnace without RF, because the popular RF-Mods already provide a powered furnace (TE, EIO, Mekanism).

For 1.8/1.9 there are [Neotech](http://minecraft.curseforge.com/projects/neotech) and [Actually Additions](http://minecraft.curseforge.com/projects/actually-additions) with electric furnaces.

**Comment by ghost** [comment]
I'm working on a an infrastructure-light pack. I found NeoTech's recipes to be too expensive, even with Dense Ores (plus the author made magnets attract fireballs, arrow and creepers %) ). I'm trying Actually Additions, but haven't found the black quartz yet. Basically, I thought Furnus might go well with Progressive Automation.
